### ISSUE TITLE
Device tree overlay rpi-display-overlay.dts does not work with kernel version 5.4

### ISSUE THREAD

**Issue by DivingIvan** [HWHardsoft/AZ-Touch-Pi0-Weather#3]
Following upgrade of Raspberry Pi OS to kernel version 5.4, the device tree overlay rpi-display-overlay.dts no longer works.

The device tree overlay requires to be modified as follows:-

Change line:

`reset-gpios = <&gpio 17 0>;`

to:

`reset-gpios = <&gpio 17 1>;`

Change line:

`led-gpios = <&gpio 18 0>;`

to:

`led-gpios = <&gpio 18 1>;`

Change line:

`pendown-gpio = <&gpio 27 0>;`

to:

`pendown-gpio = <&gpio 27 1>;`

**Comment by HWHardsoft** [comment]
Is solved now. Drivers for Raspbian OS and Raspbian Buster are available now.
